homeassistant:
  name: Home
  latitude: 55.7558
  longitude: 37.6173
  elevation: 200
  unit_system: metric
  currency: RUB
  country: RU
  time_zone: Europe/Moscow

logger:
  default: info

frontend:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
