homeassistant:
  name: Home
  latitude: 0
  longitude: 0
  elevation: 0
  unit_system: metric
  currency: RUB
  country: RU
  time_zone: Europe/Moscow

http:
  server_host: 0.0.0.0
  server_port: 8123
logger:
  default: info
  logs:
    homeassistant.components.go2rtc.server: error
